### ISSUE TITLE
Market Intelligence API missing from portal?

### ISSUE THREAD

**Issue by logikblok** [InternationalTradeAdministration/developerportal#100]
Hi I can't seem to find https://api.trade.gov/apps/store/ita/resources#market-intelligence-api 

In the developer portal? Is it missing or perhaps no longer in support?

**Comment by kbecht** [comment]
Unfortunately, the source data for this API is not currently available to us. We are working with the digital team to determine the appropriate source data for this API. We hope to have a better update available for you soon.

**Comment by logikblok** [comment]
Thanks look forward to it.
