### ISSUE TITLE
Search Result related issue

### ISSUE THREAD

**Issue by WebsSpider943** [InternationalTradeAdministration/developerportal#102]
Hello Sir,
I have checked one name in "ofac.finra.org". It provide exact_matches and all_matches with details.
I have used your API for getting details from Consolidated Screening List. I have passed same name in this API but I can not getting "All_matches" result. I only return "Exact_matches". I use below API for this.

Example : https://api.trade.gov/gateway/v1/consolidated_screening_list/search?q=Dawood

Please provide the solution.

Thanks & Regards,
Jay

**Comment by kbecht** [comment]
I am unclear as to what you are asking. When using our API, there are two different ways to search, fuzzy=off (exact match only) and fuzzy=on (fuzzy searching enabled). When searching for "dawood" with fuzzy=off, I receive 2 results. If I run the same search with fuzzy=on, then there are 14 results. 

You can learn more about the Consolidated Screening List parameters, including fuzzy searching at https://api.trade.gov/apps/store/site/pages/doc-viewer.jag?docName=Search%20Parameters%20for%20Consolidated%20Screening%20List%20Sources&name=ConsolidatedScreeningListAPI&version=v1&

If this did not answer your question, please let me know.

Kim

**Comment by WebsSpider943** [comment]
I have checked one name "shi zhang" in API and [Ofac Finra](https://ofac.finra.org/#/List). Both result are different. I also use fuzzy_name=true but not provide proper result.

Please see below images.
![Screenshot_1](https://user-images.githubusercontent.com/59221013/74846785-1783df80-5357-11ea-8b85-300b274f684b.jpg)
![API](https://user-images.githubusercontent.com/59221013/74846796-1b176680-5357-11ea-94b8-90c0bb4a7d65.jpg)

**Comment by WebsSpider943** [comment]
I have checked one name "shi zhang" in API and [Ofac Finra](https://ofac.finra.org/#/List). Both result are different. I also use fuzzy_name=true but not provide proper result.

Please see below images.
![Screenshot_1](https://user-images.githubusercontent.com/59221013/74846785-1783df80-5357-11ea-8b85-300b274f684b.jpg)
![API](https://user-images.githubusercontent.com/59221013/74846796-1b176680-5357-11ea-94b8-90c0bb4a7d65.jpg)

**Comment by WebsSpider943** [comment]
I have checked one name "shi zhang" in API and [Ofac Finra](https://ofac.finra.org/#/List). Both result are different. I also use fuzzy_name=true but not provide proper result.

Please see below images.
![Screenshot_1](https://user-images.githubusercontent.com/59221013/74846785-1783df80-5357-11ea-8b85-300b274f684b.jpg)
![API](https://user-images.githubusercontent.com/59221013/74846796-1b176680-5357-11ea-94b8-90c0bb4a7d65.jpg)

**Comment by kbecht** [comment]
There are a couple of things going on here. 

First, the search that you are using is produced by a company called FINRA and is not OFAC. I do not know any customizations that FINRA may be executing within their search. The OFAC search from the U.S. Department of Treasury is available at https://sanctionssearch.ofac.treas.gov/.

I used the OFAC search from Treasury to search for "shi zhang" and ithe match from FINRA's search was found with a score of 78. It is actually matching on "Zhang WEI". Our fuzzy searching does comparisons on single token matches. Changing "shi" to "wei" is more than a single token search and is not found within our search. I have attached documentation on how our fuzzy searching works.

Please let me know if you have any additional questions.

[fuzzy_name_scoring 01022018.pdf](https://github.com/InternationalTradeAdministration/developerportal/files/4226388/fuzzy_name_scoring.01022018.pdf)

**Comment by WebsSpider943** [comment]
Hello Sir,

I clearly understand what you say. but I have one question about (fuzzy_name =true) this. I have search one name "Rakesh" using API. I found 17 records from API. I have checked result json and I found that "Rakesh" name not found or  not exist in these results Why ?. How can it fetch 17 records. I have search name "Rakesh" but can not found.......Please checked this issue before placing any comment.

Please see below image. Please checked this issue on postman.

![image](https://user-images.githubusercontent.com/59221013/75011244-25477b00-54a5-11ea-9088-dcf0494d8d80.png)
 
Thanks & Regards,
Jay

**Comment by kbecht** [comment]
What you are executing is a single token search with fuzzy turned on. The single token matching is described in the documentation that I had previously attached. Below is an explanation as to why the first 5 results were included:

**1 - Gupta, Rajesh (score 95, adjusted score 84)** - under the substitution rule, the K is replaced with a J - rajesh becomes rakesh
**2 - Albanian National Army (score 90, adjusted score 83)** - An alternate name is AKSH, under the insertion rule, R and E are added and aksh becomes rakesh
**3 - Ervin Danesh Aryan Company (score 90, adjusted score 79)** - the match is on Danesh and under the substitution rule, the D becomes an R and the N becomes a K - danesh becomes rakesh
**4 - Jund Al-Khilafah In Tunisia (score 90, adjusted score 70)** - An alternate name is Daesh Tunisia; the match is on Daesh. Using the substitution rule and the insertion rule, the D is replaced with an R and the K is inserted - daesh becomes rakesh
**5 - Prakash, Neil Christopher (score 90, adjusted score 67)** - the match is on Prakash, using the deletion rule and the replacement rule, the P is deleted and the second A is replaced with an E - prakash becomes rakesh

If you have any questions about the remaining 17, please let me know and I will be happy to explain how they match.
