### ISSUE TITLE
We receive 502 errors when we use OFAC api

### ISSUE THREAD

**Issue by grandmair40** [InternationalTradeAdministration/developerportal#104]
Hi , We receive 502 errors from time to time. 
There is no pattern but sometimes request returns correct results and sometimes it returns 502 for the same data
example:
GET  https://api.trade.gov/gateway/v1/consolidated_screening_list/search?name=John John&countries=US&fuzzy_name=true
accept: application/json
Authorization: Bearer <yourtoken>

The full response is

GET https://api.trade.gov/gateway/v1/consolidated_screening_list/search?name=John+John&countries=US&fuzzy_name=true

HTTP/1.1 502 Bad Gateway
Date: Wed, 26 Feb 2020 14:26:33 GMT
Content-Type: text/html
Content-Length: 173
Connection: keep-alive
Server: nginx/1.14.2
Strict-Transport-Security: max-age=31536000

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr>
<center>nginx/1.14.2</center>
</body>
</html>

Response code: 502 (Bad Gateway); Time: 383ms; Content length: 173 bytes

**Comment by heitmanga** [comment]
Also seeing this behavior, but not time to time - all calls are returned with 502 from roughly 18:00 CST, 25 FEB 2020. This includes calls by our internal clients as well as from the API Console, here:

https://api.trade.gov/apps/store/apis/info?name=ConsolidatedScreeningListAPI&version=v1&provider=dataservices@trade.gov#tab1

There are no service interruptions listed here :
https://api.trade.gov/apps/store/ita/service-status

**Comment by grandmair40** [comment]
Yes , now we also return ONLY 502s.  I think the system is down or in error state at the moment

**Comment by heitmanga** [comment]
As of 10:37 CST, the issue appears to have been resolved. We are getting successful (200) results as expected via internal client, POSTMAN and API Console testing.

**Comment by kbecht** [comment]
We were experiencing a problem with the system, which has since been resolved. Please let us know if you are continuing to experience errors.
