### ISSUE TITLE
Consolidated Screening List verses Supplement No. 4 to Part 744 - ENTITY LIST

### ISSUE THREAD

**Issue by BrianRolnick** [InternationalTradeAdministration/developerportal#105]
We did a search for a company in the Consolidated Screening list inputing a name that is listed on the Supplement Entity list.
The Consolidated Screening list came up as none found.

**Comment by kbecht** [comment]
We received your email with the details of your question. I have already forwarded it to our technical team for clarification. We will respond shortly.
