### ISSUE TITLE
is there any way to raise the api request quota?

### ISSUE THREAD

**Issue by samuelail** [InternationalTradeAdministration/developerportal#106]
As listed on the dashboard, there is a 100 request per minute limit per token. This will work just fine for small to medium services looking to run ofac checks. larger services like mine however, might run into some issues here. My question is, is there any way to raise that limit?

**Comment by jamesisaacs** [comment]
Hi @samuelail. You can bulk download all the entries in csv, tsv or json format in case that helps. Here's a link to more information including the downloadable file links. 

https://www.trade.gov/consolidated-screening-list

Please contact dataservices@trade.gov if you have additional questions.
