### ISSUE TITLE
Service Outage

### ISSUE THREAD

**Issue by bjainelanders** [InternationalTradeAdministration/developerportal#113]
Data service  seems to be down for more than 2 hours today

https://internationaltradeadministration.github.io/DevPortalMessages/service-status

https://secure-stats.pingdom.com/t6cabozt4r7f/5826328

**Comment by jamesisaacs** [comment]
@bjainelanders, thanks for getting in touch. We had an unusual number of invalid requests that clogged the data service. We're looking to prevent future outages of this kind.
