### ISSUE TITLE
Links to download CSL as CSV, TSV no longer work

### ISSUE THREAD

**Issue by jfaunt** [InternationalTradeAdministration/developerportal#114]
The [ITA Consolidated Screening List](https://www.trade.gov/consolidated-screening-list) has links to download the CSL in CSV and TSV format. The links recently stopped working. I have been downloading this daily for years from [this link (with API key removed for this post)](https://api.trade.gov/consolidated_screening_list/search.csv?api_key=) which also stopped working a few days ago. Where/how can I get the CSL downloaded in CSV format?

**Comment by jamesisaacs** [comment]
@jfaunt Here's the link to the downloadable CSL in CSV format:

http://api.trade.gov/static/consolidated_screening_list/consolidated.csv

No API key is needed.
