### ISSUE TITLE
Scan new CSL API for different types - individual\company

### ISSUE THREAD

**Issue by mazitbehalf** [InternationalTradeAdministration/developerportal#120]
We are integrating with the new CSL API and cannot find a way in the params to say if we search for individuals OR companies. 
In the previous API there was a parameter called: 'type' which consisted of the following values: 'Individual', 'Entity'.

How can I filter based on it in the new API?
Thanks!

**Comment by edsp-david** [comment]
@mazitbehalf We are going to add filter by type.
We will reply to your email when it's available.
