### ISSUE TITLE
Periodically empty responses received from Service for any query  

### ISSUE THREAD

**Issue by conradoc** [InternationalTradeAdministration/developerportal#121]
It seems that every once in a while service is up responding 200 but not returning results for any query (empty response). 
We've seen this behaviour Monday 15 and Monday 29 of November  and wondering if this is a normal schedule process or if a temporal error.  It seems that the databases is completely empty at that point.

This might have a large impact since at this point, there is no way to know if an empty response corresponde with correctly to no matches or if this issue is happening again.

**Comment by jamesisaacs** [comment]
Hi @conradoc. Thank you for reporting this issue. Which API endpoint did you receive these empty responses from? We currently have two live APIs. It sounds like a problem we've noticed with the old API but I want to make sure.

If you haven't already, please see the announcement here:

https://developer.trade.gov/csl-api-is-changing

**Comment by conradoc** [comment]
Hi @jamesisaacs. Thank you for your quick response.  

This issue is happening on the **new one** _https://data.trade.gov/consolidated_screening_list/v1/search_. We have been using more or less the same set of names to do our tests as part of the integration efforts. 

We noticed the issue happened twice in the recent weeks and it last only for a few hours  apparently, after that period the same query start returning results again. But during the occurrence of the issue, no matter what name is used, it always return an empty response.

**Comment by edsp-david** [comment]
@conradoc Please send us an email with your account information to dataservices@trade.gov so that we can look at your requests.
