### ISSUE TITLE
Consolidated Screening List V1 - Status code: 410

### ISSUE THREAD

**Issue by devGBG** [InternationalTradeAdministration/developerportal#124]
![Screenshot 2021-12-14 135005](https://user-images.githubusercontent.com/96119830/145993027-b51b1a5f-5a6a-40d7-99d4-7da8205edf8d.png)

The service is not accessible. 

Reason: CORS header 'Access-Control-Allow-Origin' missing

Service URL: https://api.trade.gov/gateway/v1/consolidated_screening_list/search?size=20&offset=0

**Comment by jamesisaacs** [comment]
@devGBG That API has been deprecated. Please visit https://developer.trade.gov to sign up to use the new API and for general information. Feel free to contact us at dataservices@trade.gov with questions.
