### ISSUE TITLE
Always return the same data when hit URL from postmen or HTTP client, also Full load not available on https://data.trade.gov/consolidated_screening_list/v1/search

### ISSUE THREAD

**Issue by HemantVerma009** [InternationalTradeAdministration/developerportal#125]
Hi Team,
Earlier side/api not available and now we are connecting to new API url, we are always getting the same data in the response. can you please advise on the same?
Also full-load is not available in new API's so how can we load the complete data? when offset also has the limit of 1000 only?
Awaiting for your help.

https://data.trade.gov/consolidated_screening_list/v1/search

Thanks & Regards
Hemant Verma
hverma@globalindustrial.com

**Comment by jamesisaacs** [comment]
Hi @HemantVerma009. You can find downloadable files containing the full data set here: https://www.trade.gov/consolidated-screening-list. Please contact us at dataservices@trade.gov if you have additional questions.

**Comment by HemantVerma009** [comment]
Hi Team/Jamesisaacs,
Thanks for providing the steps to download full data set, Here I can download the fullLoad but We need to achieve the same from API call, as this we need to setup as schedule activity.
Can you Please advise?

Also there is one more point that we are always getting the same set of records when call the API from postman or HTTP client but this is working fine on 'https://www.trade.gov/consolidated-screening-list' side?

Thanks & Regards
