### ISSUE TITLE
Hi Team/Jamesisaacs,

### ISSUE THREAD

**Issue by HemantVerma009** [InternationalTradeAdministration/developerportal#126]
Hi Team/Jamesisaacs,
Thanks for providing the steps to download full data set, Here I can download the fullLoad but We need to achieve the same from API call, as this we need to setup as schedule activity.
Can you Please advise?

Also there is one more point that we are always getting the same set of records when call the API from postman or HTTP client but this is working fine on 'https://www.trade.gov/consolidated-screening-list' side?

Thanks & Regards
Hemant Verma
hverma@globalindustrial.com

_Originally posted by @HemantVerma009 in https://github.com/InternationalTradeAdministration/developerportal/issues/125#issuecomment-994708279_

**Comment by jamesisaacs** [comment]
Hi @HemantVerma009. This API limits the maximum offset for results to 1000. See https://developer.trade.gov/api-details#api=consolidated-screening-list for more information.

Please provide an example of the issue you're having receiving the same records when making an API call? Let's continue this correspondence by email. You can reach me at dataservices@trade.gov.

Regards,

James
