### ISSUE TITLE
Want to have "matched pattern" returned results for Consolidated List search

### ISSUE THREAD

**Issue by panjung** [InternationalTradeAdministration/developerportal#129]
Hi, before the recent API upgrade, there was "matched pattern" existing in the results.  That was very useful to recognize quickly whether the matches are significant or something we can ignore.   How or where can we get the "matched pattern" field at the current API?

**Comment by jamesisaacs** [comment]
Hi @panjung. I've logged your request. Sorry for the slow response. Please feel free to contact us at dataservices@trade.gov for a quicker response.
