### ISSUE TITLE
Clearer info about rate limit

### ISSUE THREAD

**Issue by tupizz** [InternationalTradeAdministration/developerportal#131]
Hello.
I wonder what is the actual rate limit happening on the API side.
I've seen 100calls/minute, but that's not true, at least not for my API tokens.

**Comment by rjpereira** [comment]
Also interested in the answer.

**Comment by jamesisaacs** [comment]
@tupizz @rjpereira Thank you for using the CSL API. The rate limit is 100 rpm. We recommend spreading it out your requests to ~3 requests every 2 seconds if you're receiving 429s.

You might also find one of the downloadable files containing the full CSL helpful. You can find them here: 

https://www.trade.gov/consolidated-screening-list
 
If you have additional questions/concerns please let us know at dataservices@trade.gov for the quickest response.
  
James Isaacs
 
Data Services Team
Office of the Chief Information Officer (OCIO) | Technology Transformation & Data Services (TTDS)
U.S. Department of Commerce | International Trade Administration
