### ISSUE TITLE
[Question] Will static links to the entire CSL remain "subscription"-free?

### ISSUE THREAD

**Issue by jlhall** [InternationalTradeAdministration/developerportal#135]
Referring to the link(s) here:

https://api.trade.gov/static/consolidated_screening_list/consolidated.json
https://api.trade.gov/static/consolidated_screening_list/consolidated.tsv
https://api.trade.gov/static/consolidated_screening_list/consolidated.csv

#117 asked this question a little less than a year ago, but with the recent communication from ITA, it's unclear if the static endpoints may now be moving from public to being behind the subscription wall (or just migrating subdomains?) -

> Last October we released a new, upgraded ITA Developer Portal. This upgrade provides increased platform stability and improved security, providing you, our customers, with a more robust API platform. Last Fall we moved the Consolidated Screening Lists (CSL) API. We have now moved all of our remaining APIs to the new, upgraded portal. The APIs are now all available in the new platform and we ask that you spend the next two weeks moving any applications you have the to APIs on the new platform.
>
> What this Means for You
>
> Accessing our APIs via our new ITA Developer Portal will require all users to request a subscription for accessing our APIs.
>
> **_The current APIs will continue to work until close of business (5:00 pm Eastern Standard Time) September 16, 2022, when the current system will be turned off._**
>
> **_Please explore our new ITA Developer Portal and subscribe to our APIs. These subscriptions are free and will continue to provide you with access to all of our APIs._**
>
> As this is a new system, you will HAVE TO make some code changes in order to receive results. We did our best to minimize changes, and we apologize for any inconvenience. Please see the new documentation for each of our APIs for the related changes.
>
> If you have any questions or concerns about obtaining a subscription or using the APIs, please reach out to us at DataServices@trade.gov.
>
> Four Action Items to Not Lose API Services
>
> You must register for an account. Instructions on how to register (if needed) are below.
> You must Subscribe to the API. Instructions on how to subscribe to our APIs may be found on the portal.
> You must make necessary code changes and test.
> You must change your application code by end of business September 16, 2022 (5:00 pm Eastern Standard Time).
> Note: Due to the cost of running two services at the same time, September 16, 2022 is the final date. There will not be any extensions.

It has always been a little unclear in official communications if the static list endpoints are considered part of the "CSL API" by the folks writing the comms (by most technical definitions of an API they would not be 😄...right? Right?!!)

This and the previous answer suggests to us that we can assume with safety that the static public links are not part of the API and so phrasing like "the current system will be turned off" just refer to the previous version of the API / authentication & authorization patterns reaching EOL - but we want to be diligent & clear. Is this correct, the static links remain?

Alternately, if the answer is that these links are "migrating", should we expect to find them at the following URLs?

https://data.trade.gov/static/consolidated_screening_list/consolidated.json
https://data.trade.gov/static/consolidated_screening_list/consolidated.tsv
https://data.trade.gov/static/consolidated_screening_list/consolidated.csv

i.e. based off the new CSL API URL:
```
https://data.trade.gov/consolidated_screening_list/v1/search[?name][&fuzzy_name][&sources]
[&types][&countries][&address][&city][&state][&postal_code][&full_address][&offset][&size]
```

Thank you for your diligent work modernizing and improving the US Govt's data systems 👍

**Comment by jamesisaacs** [comment]
Hi @jlhall. Thank you for the feedback! The static endpoints will be migrating but they will not be behind the subscription wall. The exact URLs haven't been determined yet but we've discussed having them be exactly what you expect. That will be decided this week. We'll send out an update once the static files have been moved.

**Comment by ashmomin** [comment]
https://api.trade.gov/gateway/v1/consolidated_screening_list/search?

Is this api already closed? it is not working

**Comment by jlhall** [comment]
> https://api.trade.gov/gateway/v1/consolidated_screening_list/search?
> 
> Is this api already closed? it is not working

@ashmomin  Yep, as referenced at the very top of the main api.trade.gov page:

> The Consolidated Screening List API has moved!
You can access the new CSL API via our [new ITA Developer Portal](https://developer.trade.gov/).
Please read the [changelog for the new CSL API](https://developer.trade.gov/api-changelog#api=consolidated-screening-list).

That api was migrated "first" a decent while ago, you can find details on the [migrated endpoint via the new ITA Developer Portal's API Listing](https://developer.trade.gov/api-details#api=consolidated-screening-list&operation=search).

**Comment by jlhall** [comment]
@jamesisaacs Sorry to be a bother, but we have folks internally asking for a rough timeline on link migration; has that discussion you mentioned happened yet or is there anything to share? Chur mate 😉

**Comment by jlhall** [comment]
Following up for anyone reading, an email from ITA arrived around 3:33 PM GMT confirming the links are migrated but to a `downloadable_consolidated_screening_list` path on data.trade.gov:

> We have upgraded our infrastructure to be more scalable and will be performing maintenance on the Consolidated Screening List (CSL) this weekend.
> As part of this upgrade, we are changing the URLs for the downloadable CSL files.  The new files will be available at
> CSV: [https://data.trade.gov/downloadable_consolidated_screening_list/v1/consolidated.csv](https://lnks.gd/l/eyJhbGciOiJIUzI1NiJ9.eyJidWxsZXRpbl9saW5rX2lkIjoxMDIsInVyaSI6ImJwMjpjbGljayIsImJ1bGxldGluX2lkIjoiMjAyMjA5MzAuNjQ0NzUyNDEiLCJ1cmwiOiJodHRwczovL2RhdGEudHJhZGUuZ292L2Rvd25sb2FkYWJsZV9jb25zb2xpZGF0ZWRfc2NyZWVuaW5nX2xpc3QvdjEvY29uc29saWRhdGVkLmNzdiJ9.fmGiv4UVlR4vqU6oQWP_pzfA9-ktqLFSWxrsYL97pw4/s/977965354/br/144993174450-l)
> TSV: [https://data.trade.gov/downloadable_consolidated_screening_list/v1/consolidated.tsv](https://lnks.gd/l/eyJhbGciOiJIUzI1NiJ9.eyJidWxsZXRpbl9saW5rX2lkIjoxMDMsInVyaSI6ImJwMjpjbGljayIsImJ1bGxldGluX2lkIjoiMjAyMjA5MzAuNjQ0NzUyNDEiLCJ1cmwiOiJodHRwczovL2RhdGEudHJhZGUuZ292L2Rvd25sb2FkYWJsZV9jb25zb2xpZGF0ZWRfc2NyZWVuaW5nX2xpc3QvdjEvY29uc29saWRhdGVkLnRzdiJ9.vIzAcPLhOX0XCu0rxfZ3j8Gc7JYYx2YOIBeIUoAgi44/s/977965354/br/144993174450-l)
> JSON: [https://data.trade.gov/downloadable_consolidated_screening_list/v1/consolidated.json](https://lnks.gd/l/eyJhbGciOiJIUzI1NiJ9.eyJidWxsZXRpbl9saW5rX2lkIjoxMDQsInVyaSI6ImJwMjpjbGljayIsImJ1bGxldGluX2lkIjoiMjAyMjA5MzAuNjQ0NzUyNDEiLCJ1cmwiOiJodHRwczovL2RhdGEudHJhZGUuZ292L2Rvd25sb2FkYWJsZV9jb25zb2xpZGF0ZWRfc2NyZWVuaW5nX2xpc3QvdjEvY29uc29saWRhdGVkLmpzb24ifQ.6l3b0Q5cKIQD5XpOK0w41TtcTevuXiTM-FUUxaDNhBo/s/977965354/br/144993174450-l)
> We have added redirects to these new URLs so most users will not notice the change. However, if you have coded these URLs into an application and your code throws an error, you may need to update the links in your application.
> Additionally, during this maintenance, we will be temporarily freezing the automatic updates to the CSL and will send another email early next week once the automatic updates have resumed. The API and the downloadable files will continue to operate as normal during this maintenance period.
> If you have any questions about this maintenance period, the CSL downloadable files, or about our APIs, please contact us at [DataServices@trade.gov](mailto:DataServices@trade.gov). Thank you.
> Kimberly J. Becht
> Lead, Data Service Team
> Office of the Chief Information Officer (OCIO)
> International Trade Administration (ITA)
