### ISSUE TITLE
Static CSL file contains expired entries of the Nonproliferation Sanctions List

### ISSUE THREAD

**Issue by aebtradecompliance** [InternationalTradeAdministration/developerportal#138]
The following static files are meant:
https://data.trade.gov/downloadable_consolidated_screening_list/v1/consolidated.json
https://data.trade.gov/downloadable_consolidated_screening_list/v1/consolidated.tsv
https://data.trade.gov/downloadable_consolidated_screening_list/v1/consolidated.csv

Since 10/07/2022, entries can be found in these files under the source "Nonproliferation Sanctions (ISN) - State Department" which have already expired according to the "BUREAU OF INTERNATIONAL SECURITY AND NONPROLIFERATION". 
These expired entries also do not have the attribute "end_date" in the files (cf. [consolidated-screening-lists.json](https://github.com/InternationalTradeAdministration/developerportal/blob/gh-pages/api/consolidated-screening-lists.json).) 

According to [the Master Sanctions Chart](https://www.state.gov/wp-content/uploads/2022/10/MASTER-Sanctions-10.7.22.pdf) of the "BUREAU OF INTERNATIONAL SECURITY AND NONPROLIFERATION", the entry for "Eren Carbon Graphite Industrial Trading Company, Ltd." is expired on 02/03/2020, but is still shown as active in the current CSL file.

In the delivered file versions prior to 10/07/2022, expired entries for this source were simply removed from the file. 
Could you please ensure that the end_date attribute is specified or that the expired entries are removed from the results list?

**Comment by jamesisaacs** [comment]
@aebtradecompliance Thank you for raising this issue. I've logged it in our system. We will reach out to the data providers. If you have additional concerns please feel free to contact us at dataservices@trade.gov.
