### ISSUE TITLE
Deviating composition of the "alt_names" attribute in CSL since 10/07/2022

### ISSUE THREAD

**Issue by aebtradecompliance** [InternationalTradeAdministration/developerportal#139]
Since 10/07/2022, we have noticed a different composition of the attribute "alt_names" (cf. [consolidated-screening-lists.json](https://github.com/InternationalTradeAdministration/developerportal/blob/gh-pages/api/consolidated-screening-lists.json).)

Records from the source "Nonproliferation Sanctions (ISN) - State Department" now contain arrays with a size of one for the attribute "alt_names", 
where the only entry is a string separating several "alt_names" with a comma. 
Other sources use a semicolon here as a delimiter or else show each alt_name as a separate array entry.

Current version:
![image](https://user-images.githubusercontent.com/115551097/195098372-51fca26d-731b-4ae9-afb1-6bed2b118d8b.png)

Previous version:
![image](https://user-images.githubusercontent.com/115551097/195098802-53e57e7c-344a-440d-bad1-47e96e23ec33.png)

For records from the source "Entity List (EL) - Bureau of Industry and Security", 
the array size of the attribute "alt_names" is one for each record. 
Even if there is no alt_name for the record, there is now an empty string as an entry in the array. 

![image](https://user-images.githubusercontent.com/115551097/195099332-aec4ac76-d4a1-41ff-b51c-839b9b4020cb.png)

Previously, the array for the "alt_names" attribute was empty in this case. 
There were also entries for this source with an array size greater than 1 for the attribute "alt_names".

Would it be possible to standardise the format again?

**Comment by jamesisaacs** [comment]
Hi @aebtradecompliance. Thank you for your feedback! I have put in a fix for the ISN data and raised the question of changing the EL data to match. Thank you again. Please feel free to contact us at dataservices@trade.gov with additional questions.
