### ISSUE TITLE
SDN List not included

### ISSUE THREAD

**Issue by gallagher-sean** [InternationalTradeAdministration/developerportal#146]
As of 5/6/2024 at 1:38 PM, the Consolidated Screening List does not include any values from Treasury screening lists - see below screenshot for reference.
<img width="425" alt="Screenshot 2024-05-06 133858" src="https://github.com/InternationalTradeAdministration/developerportal/assets/51179053/c0b54141-6132-4d73-9c77-a7bcf8a1fb79">

**Comment by jlhawn** [comment]
I counted the number of entries from different sources on 2024/05/03 to compare with today's (2024/05/06). There's ~15,000 entries missing from SDN and SSI sources:

```
In [14]: source_counts_0503
Out[14]:
Counter({'Specially Designated Nationals (SDN) - Treasury Department': 14973,
         'Entity List (EL) - Bureau of Industry and Security': 2778,
         'ITAR Debarred (DTC) - State Department': 755,
         'Denied Persons List (DPL) - Bureau of Industry and Security': 568,
         'Sectoral Sanctions Identifications List (SSI) - Treasury Department': 288,
         'Unverified List (UVL) - Bureau of Industry and Security': 192,
         'Nonproliferation Sanctions (ISN) - State Department': 138,
         'Palestinian Legislative Council List (PLC) - Treasury Department': 78,
         'Military End User (MEU) List - Bureau of Industry and Security': 70,
         'Non-SDN Chinese Military-Industrial Complex Companies List (CMIC) - Treasury Department': 68,
         'Non-SDN Menu-Based Sanctions List (NS-MBS List) - Treasury Department': 13,
         'Capta List (CAP) - Treasury Department': 1,
         'Foreign Sanctions Evaders (FSE) - Treasury Department': 1})

In [15]: source_counts_0506
Out[15]:
Counter({'Entity List (EL) - Bureau of Industry and Security': 2778,
         'ITAR Debarred (DTC) - State Department': 755,
         'Denied Persons List (DPL) - Bureau of Industry and Security': 568,
         'Unverified List (UVL) - Bureau of Industry and Security': 192,
         'Nonproliferation Sanctions (ISN) - State Department': 138,
         'Palestinian Legislative Council List (PLC) - Treasury Department': 78,
         'Military End User (MEU) List - Bureau of Industry and Security': 70,
         'Non-SDN Chinese Military-Industrial Complex Companies List (CMIC) - Treasury Department': 68,
         'Non-SDN Menu-Based Sanctions List (NS-MBS List) - Treasury Department': 13,
         'Foreign Sanctions Evaders (FSE) - Treasury Department': 1,
         'Capta List (CAP) - Treasury Department': 1})

In [16]: set(source_counts_0503.keys()) - set(source_counts_0506.keys())
Out[16]:
{'Sectoral Sanctions Identifications List (SSI) - Treasury Department',
 'Specially Designated Nationals (SDN) - Treasury Department'}
 ```

**Comment by kbecht** [comment]
We are aware of the problem and are working on a solution. We recently sent out a message to our subscribers about the problem. The message is included below for your reference.

> We are currently experiencing a problem with the Specially Designated Nationals (SDN) List portion of the Consolidated Screening List (CSL).
> 
> We are actively working to get this issue resolved.
> 
> Until we are able to resolve it, please utilize the links below for access to SDN information at the Office of Foreign Assets Control (OFAC) website:
> 
> [Sanctions List Service (SLS)](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fofac.treasury.gov%2Fsanctions-list-service&data=05%7C02%7Ckimberly.becht%40trade.gov%7C9adf27ed695b4182ca5a08dc6e11665c%7Ca1d183f26c7b4d9ab9945f2f31b3f780%7C1%7C0%7C638506268245145954%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=DwoTy7EB%2Bx8REle%2FAgOTDJdVKGnGPnVqHNOPISP2sGQ%3D&reserved=0) - Information on OFAC’s SLS
> 
> [Data Center – SDN List](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsanctionslist.ofac.treas.gov%2FHome%2FSdnList&data=05%7C02%7Ckimberly.becht%40trade.gov%7C9adf27ed695b4182ca5a08dc6e11665c%7Ca1d183f26c7b4d9ab9945f2f31b3f780%7C1%7C0%7C638506268245151301%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ihhO0z6%2BKaQvVJkgwg%2BrVCeBS6FOrmkY6HhTA0L20R8%3D&reserved=0) - Download the SDN List
> 
> [Sanctions List Search Tool](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsanctionssearch.ofac.treas.gov%2F&data=05%7C02%7Ckimberly.becht%40trade.gov%7C9adf27ed695b4182ca5a08dc6e11665c%7Ca1d183f26c7b4d9ab9945f2f31b3f780%7C1%7C0%7C638506268245156588%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=RzbNGNalwfcFIu0TOVJCFLsTKQxmQySm65RWgnhFySQ%3D&reserved=0) - Search OFAC Sanctions Lists, including the SDN list
> 

If you are not a subscriber, I recommend you [sign up to receive our notifications](https://public.govdelivery.com/accounts/USITATRADE/subscriber/new?topic_id=USITATRADE_1704) when we announce major changes and outages related to the APIs. If you have any other questions, you can also reach out to us at DataServices@trade.gov.

**Comment by jlhawn** [comment]
Thank you for the update!On May 6, 2024, at 15:49, Kimberly Becht ***@***.***> wrote:﻿
We are aware of the problem and are working on a solution. We recently sent out a message to our subscribers about the problem. The message is included below for your reference.

We are currently experiencing a problem with the Specially Designated Nationals (SDN) List portion of the Consolidated Screening List (CSL).
We are actively working to get this issue resolved.
Until we are able to resolve it, please utilize the links below for access to SDN information at the Office of Foreign Assets Control (OFAC) website:
Sanctions List Service (SLS) - Information on OFAC’s SLS
Data Center – SDN List - Download the SDN List
Sanctions List Search Tool - Search OFAC Sanctions Lists, including the SDN list

If you are not a subscriber, I recommend you sign up to receive our notifications when we announce major changes and outages related to the APIs. If you have any other questions, you can also reach out to us at ***@***.***

**Comment by gallagher-sean** [comment]
Looks fixed to me too. Thanks!

**Comment by kbecht** [comment]
We are still working to fix the downloadable files. Once it is fully resolved, we will send a follow-up email to our subscribers. I can post one here as well.

**Comment by kbecht** [comment]
We have resolved the issue with the Specially Designated Nationals (SDN) List portion of the Consolidated Screening List (CSL). We have validated that the API, the search page on Trade.gov, and the downloadable files are all reporting the correct number of entities. 

If you have any questions, please let us know.
