### ISSUE TITLE
Consolidated Screening List - Internal Server Error

### ISSUE THREAD

**Issue by kcaligiuri** [InternationalTradeAdministration/developerportal#150]
We are receiving a Status Code 500, "Internal server error" when attempting to call data.trade.gov consolidated screening API.  Is there a known issue?

**Comment by cibains** [comment]
We have been experiencing same issue since today morning

**Comment by edsp-david** [comment]
@kcaligiuri @cibains

I am sorry about the issue that you are having with our CSL API.
We were experiencing high latency on our platform.
This issue should be fixed now.

Let us know if you are still having high latency issue.
