### ISSUE TITLE
Some queries return results for garbage queries

### ISSUE THREAD

**Issue by pyramiddig** [InternationalTradeAdministration/developerportal#30]
Some APIs don’t give an error when presented with a random string.  For example:  http://api.trade.gov/trade_leads/search?industries=asdfasdf gives 2686 results (the entire Trade Leads result set).

The methods for all of the APIs need to be updated to return zero results for garbage queries.

**Comment by jamesisaacs** [comment]
Fixed. (PT 81991302)
