### ISSUE TITLE
Clarify the number of results returned from each API

### ISSUE THREAD

**Issue by pyramiddig** [InternationalTradeAdministration/developerportal#33]
Clarify that the number of results returned from the API.  The [JSON](http://api.trade.gov/trade_events/search) indicates the total number of results available but only returns 10 results at a time.  If the developer specifies size and offset, the API returns a maximum of 100 results.  Indicate both of these limitations in the documentation for each API.

**Comment by jamesisaacs** [comment]
Closing as changed. Please see: http://developer.trade.gov/market-research-library.html.
