### ISSUE TITLE
Pulling too much data too quickly

### ISSUE THREAD

**Issue by pyramiddig** [InternationalTradeAdministration/developerportal#37]
What is our policy for pulling too much data too quickly

**Comment by nsinai** [comment]
What does "too much" and "too quickly" mean? Thanks!

**Comment by pyramiddig** [comment]
We're trying to figure that out, nsinai.  Thanks!

**Comment by pyramiddig** [comment]
We do not plan to brake data users at this time.  However, we do monitor traffic and will note unusual or detrimental activity.
