### ISSUE TITLE
Use Search.json

### ISSUE THREAD

**Issue by pyramiddig** [InternationalTradeAdministration/developerportal#38]
During usability testing it was suggested that we use http://api.trade.gov/trade_leads/search.json for our examples not http://api.trade.gov/trade_leads/search which is missing **.json**.

**Comment by jamesisaacs** [comment]
Let's make this change if we begin to support other output formats to avoid confusion; e.g. `../search.xml` will lead to an error. The documentation is clear that we currently only provide JSON output.
