### ISSUE TITLE
Incomplete dataset

### ISSUE THREAD

**Issue by m-d-e** [InternationalTradeAdministration/developerportal#40]
The API for the Consolidated Screening List is not displaying a number of names added to the Entity List in February.

It appears that all of the entities and individuals added to the list via Federal Register Notices 80 FR 22638 (http://www.gpo.gov/fdsys/pkg/FR-2015-04-23/pdf/2015-09442.pdf) and 80 FR 8524 (http://www.gpo.gov/fdsys/pkg/FR-2015-02-18/pdf/2015-03321.pdf) are not found via the API search, but do appear in the downloaded Consolidated Screening List CSV file.

I do not know if this issue is limited to the two notices (22638 & 8524) or if this is a larger issue.  Oddly, the most recent names added to the CSL in March & April do appear via the API.

Does the API provide access to the same dataset as the CSV/ASCII formatted file?  Or are you pulling data from individual lists and maintaining a separate file?

**Comment by pyramiddig** [comment]
Good afternoon m-d-e,

We too discovered this issue and have worked it out with BIS who manages the Entity List.  You should see all of the newly added names tomorrow.  We pull all of the lists directly from the groups who manage them within each source agency.

Regarding the CSV/ASCII files:  those files are managed separately but we are working with the group that manages them.  The group will be using the API to populate the two files soon.

FYI:  the CSV/ASCII do no contain the latest lists from OFAC:

1. Non-SDN Iranian Sanctions Act List = ISA
2. Palestinian Legislative Council List = PLC
3. Part 561 List = 561
4. Sectoral Sanctions Identifications List = SSI

Please let me know if you have any other questions.

Thanks,
Stuart
