### ISSUE TITLE
append countries=US returns zero results

### ISSUE THREAD

**Issue by genqiang** [InternationalTradeAdministration/developerportal#46]
https://api.trade.gov/v2/consolidated_screening_list/search?api_key={{key}}&q=Eric%20Cohen&countries=US returns zero result
but https://api.trade.gov/v2/consolidated_screening_list/search?api_key={{key}}&q=Eric%20Cohen
returns one

**Comment by pyramiddig** [comment]
Genqiang - thanks for the heads up.  I will notify the owners of the Denied Persons List (where this entity is listed) that the country is not listed.

**Comment by pyramiddig** [comment]
Hi @genqiang   It looks like the data owners addressed the issue.  Please post here if you have any other feedback.

Thanks,
Stuart
