### ISSUE TITLE
Is this still a live project?

### ISSUE THREAD

**Issue by jfaith0814** [InternationalTradeAdministration/developerportal#49]
Hi - I've sent an email help request on implementing some of the JSON data feeds in WordPress and haven't gotten a response or acknowledgement. Please let me know one way or the other if the project is still live?

Thanks,
Jim Faith

**Comment by tmhammer** [comment]
Hi Jim, yes this project is still live.  I'm not sure what happened to your help email.

**Comment by jfaith0814** [comment]
Hi Timothy – Thanks for your response and I’m happy to hear you’re still alive. For the last 8 years, I’ve been a contractor for the Overseas Private Investment Corp. (OPIC) and I met/talked with Stuart Ridgway about 18 months ago.  I tried sending an email to him also. That email bounced back as undeliverable so I assume he’s no longer with the program? In any event – here’s my issue and request for help – 

 

I’m working on TradePort.org, a non-profit, international business portal owned by the Los Angeles Area Chamber of Commerce and the San Francisco Bay Area Council (http://stage.tradeport.org/). I’ve integrated the following data feeds as content pages in WordPress (accessible in the top nav).

 

In the Library, you can find:

1. Exporting FAQs

2. Consolidated Screening List

3. De Minimis

4. Tariff Rates

 

In Market Research, 

1. Market Reports (Market Research Library)

2. Trade Leads

 

In News and Events

1. Trade News and Articles

2. Trade Events

 

We have some issues in Tariff Rates, Trade Events and Trade News. I’m not sure what’s wrong with the Tariff Rates, but the links appear to be missing in both Events and News?  

 

WordPress page for Tariff Rates: http://stage.tradeport.org/tariff-rates/

Trade Events: http://stage.tradeport.org/trade-events/ 

Trade News: http://stage.tradeport.org/trade-news/ 

 

The JSON object for Tariff Rates: http://stage.tradeport.org/trade-api.php?endpoint=tariff_rates&q=&size=10&offset=0

Trade Events: http://stage.tradeport.org/trade-api.php?endpoint=trade_events&q=&size=10&offset=0

Trade News: http://stage.tradeport.org/trade-api.php?endpoint=trade_articles <http://stage.tradeport.org/trade-api.php?endpoint=trade_articles&q=&size=10&offset=0> &q=&size=10&offset=0

 

Any suggestions or guidance would be greatly appreciated – Thanks

 

Jim Faith

Cell: 831.227.0595

**Comment by tmhammer** [comment]
With regards to the missing URLs issue, unfortunately the data providers for these endpoints do not always provide a URL (or a valid one), so I'm not sure there's much to be done for this.  Some documents will have URLs, some will not.  

 Is there another issue with Tariff Rates page other than rendering URLs?

**Comment by jfaith0814** [comment]
No – that’s it. There also missing links in the News and Articles and Events feeds.

I can see the Events feed working on BusinessUSA.gov http://business.usa.gov/events-search/ 

And News and Articles working on Think Global - http://www.think.global/trade_resources/trade_articles#.Vux9X5wrKM8

 

Am I missing something?

**Comment by jfaith0814** [comment]
I'd really like to understand why News and Events don't work on my site; as I see them working on the demos and on other sites. Can you offer any suggestions beyond "some have urls and some don't?"

Thanks,
JIm

**Comment by tmhammer** [comment]
What features of the BusinessUSA.gov and Think Global feeds are you trying to get "working", exactly?  The header links on those feeds don't seem to point back to the original source of our data, but rather to another page that's rendered elsewhere on the same site.

**Comment by jfaith0814** [comment]
I got my issue resolved - thanks for your help and wanted to close the thread. Please add me to any mail/groups you maintain.
