### ISSUE TITLE
IE 11 search issue

### ISSUE THREAD

**Issue by randula63** [InternationalTradeAdministration/developerportal#50]
We use the following site http://internationaltradeadministration.github.io/explorer/#/consolidated-screening-list-entries to seach for denied parties.  After a recent upgrade to Internet Explorer 11 the search function is no longer working.  It was working properly in IE10.

**Comment by tmhammer** [comment]
Sorry for the delay @randula63, we have been working to fix Explorer and this issue should now be resolved.
