### ISSUE TITLE
Response to high volume of API calls at once

### ISSUE THREAD

**Issue by robertopastrana** [InternationalTradeAdministration/developerportal#53]
Hello, we are planning to check our database against the ‘Consolidated Screening List’ at once. Our database contains ~600,000 records that we plan to check by API trough your servers for many consecutive hours/days. 

Please advise if this effort would need any kind of coordination with you and the best way to communicate with you. Note we are planning performing same exercise every 6-12 months. 

Thank you.

**Comment by ErikSArnold** [comment]
We do not currently have any rate limiting, but we do reserve the right to rate limit should the service degrade. As a reminder our Terms of Service is here: http://developer.trade.gov/tos.html

However, notifying us of your intention is a great thing to do and we appreciate it, plus it is more likely to eliminate any service disruption to your IP address.

Generally for testing scenarios, we do ask that you not send more than 1 query per second. It sounds like you have already planned to do that based on your question. Let us know if you have any issues.
