### ISSUE TITLE
API Access Key not working 

### ISSUE THREAD

**Issue by HanGookOhLogic** [InternationalTradeAdministration/developerportal#54]
Despite switching access keys, I still get an error message: {"error":"Unauthorized - Please get a new key at https://api.trade.gov"} whenever I try to get data.

How do I fix this since I have already tried switching keys

**Comment by govardhanhills** [comment]
Hello HanGookOhLogic,
Is your issue resolved?
We're planning to use the API from the source govt. website and wanted to know if you're still getting the same error? Thanks in advance.

**Comment by ErikSArnold** [comment]
Hello. As far as we know there are not any errors. Please let me know if you are still experiencing issues logging in.

**Comment by kbecht** [comment]
@HanGookOhLogic I just wanted to follow up to see if you are still experiencing problems. If you are, please let us know what they are.  Thanks.
