### ISSUE TITLE
ITA API standards?

### ISSUE THREAD

**Issue by rdgsa** [InternationalTradeAdministration/developerportal#55]
I would like to find out if ITA publishes standards for their internal groups for publishing APIs. Is there a point of contact you could recommend?

**Comment by ErikSArnold** [comment]
Currently, the our API publishing flows through one group, so we do try to keep consistency between the published APIs and the source content, but we don't have any standards per se for internal content groups. We do keep our eyes on emerging standards such as http://jsonapi.org/ and follow API best practices.
