### ISSUE TITLE
API search ignores address parameter

### ISSUE THREAD

**Issue by mjfrey** [InternationalTradeAdministration/developerportal#56]
When using the following API construct, I get positive search results for users that do not have an exact address match.
Is this the intended behavior of the search?  I would expect that if I provide an address I would not get a positive search result for a user with the same name but different address.

https://api.trade.gov/consolidated_screening_list/search?sources=ISN,SDN&api_key=key&type=individual&q=full name&address=foo

**Comment by ErikSArnold** [comment]
Hello. If you could send the full query, I may be able to explain it a bit better, but I believe I get your in your example above the API query is setup to be an "OR" (versus and "AND" which is what I think you were expecting).

As a result, you would receive the results that you describe below. Being able to specify an exact match in the query is a good idea though.

I'll  note it. Thank you,

Erik
