### ISSUE TITLE
ITA Data Services - Consolidated Screening List Api: invalid source information, missing data

### ISSUE THREAD

**Issue by chadhinton** [InternationalTradeAdministration/developerportal#62]
For the ITAR list, the CSL api shows that the source was last updated on 1/23/18. However, State debarred 168 individuals/entities on 4/25/18 (https://www.federalregister.gov/documents/2018/04/25/2018-08684/title-bureau-of-political-military-affairs-statutory-debarment-under-the-arms-export-control-act-and). We are utilizing the CSL api source_last_updated date to trigger an analyst to review the changes. The source_last_updated for the ITAR list is invalid and the CSL api is not listing the 168 individuals/entities from the 4/25/18 State ITAR action.

Could you help explain this discrepancy and advise if we should continue using the CSL api and underlying data for the described purposes?

Request:
curl -s 'https://api.trade.gov/consolidated_screening_list/search?api_key=SECRET'

Under the sources_used key:
    {
      "source": "ITAR Debarred (DTC) - State Department",
      "source_last_updated": "2018-01-23T16:08:46+00:00",
      "last_imported": "2018-05-09T16:03:04+00:00",
      "import_rate": "Hourly"
    }

**Comment by kbecht** [comment]
Is it only the SDN or are there additional lists you are seeing this problem with?

**Comment by chadhinton** [comment]
We also experienced and reported missing data from the ITAR list but you
already resolved that issue. There is no other inconsistency that we're
aware of at this time.

**Comment by kbecht** [comment]
I will reach out to Treasury about the SDN list. Please let me know if you experience any other issues with the CSL API being out of date.
