### ISSUE TITLE
constant 'Get New Key' request

### ISSUE THREAD

**Issue by tb-cn-coding** [InternationalTradeAdministration/developerportal#64]
Hi there!

I just began using the API but haven't been able to due to key issues. I received a key and used it in forming an API request, but got this error:

{"error":"Unauthorized - Please get a new key at https://api.trade.gov"}

when I get a new key, I get the same error. I believe it either is some internal issue on your end or (more likely), on my end improperly inputting my key.

This is an example of how I'm inputting the key (with a fake key for security):
https://api.trade.gov/consolidated_screening_list/search?api_key={sTsfkjhtWDHaij93JFkj}

**Comment by kbecht** [comment]
If you are using the brackets around your API key, please remove them. It should look like this:
https://api.trade.gov/consolidated_screening_list/search?api_key=sTsfkjhtWDHaij93JFkj

Please let me know if that does not solve your problem.

**Comment by kbecht** [comment]
I'm glad I could help. If there's anything else we can help with, please let us know.
