### ISSUE TITLE
usage of Api parameter "SIZE=-1" along with other filters

### ISSUE THREAD

**Issue by infoBridge** [InternationalTradeAdministration/developerportal#65]
we are evaluating API.
Test API call parameters and results.
**Api-callA**: ....consolidated_screening_list/search?api_key=XXX&size=100&countries=AF&fuzzy_name=false&sort=name:desc
api returns: count = 114 and results = 100
Result: Ok

To get all data/ results I tried "size=-1" along with other parameters like countries=AF&fuzzy_name=false&sort=name:desc
**Api-callB**: ....consolidated_screening_list/search?api_key=XXX&size=-1&countries=AF&fuzzy_name=false&sort=name:desc
api returns: count = 9416 and results = 9416. 
Result: Its noticed that the result includes records of other Countries also and not just as "AF".

Is this a bug or expected behavior? If so then please share a link to refer more.
Aim is to avoid multiple AP calls and get most data as per the filters like Country etc. From your help doc/ online knowledgeBase i learnt about "size=-1"

thanks

**Comment by kbecht** [comment]
I am having a hard time reproducing this problem. Each time I try, I am receiving "total": 114. 9416 is the full result of the Consolidated Screening List without any filters. Try this string, replacing with your api_key:

https://api.trade.gov/consolidated_screening_list/search?api_key=XXX&size=100&countries=AF&fuzzy_name=false&sort=name:desc

**Comment by infoBridge** [comment]
https://api.trade.gov/consolidated_screening_list/search?api_key=XXX&size=100&countries=AF&fuzzy_name=false&sort=name:desc
This returns 114 which is correct.

Please change "size=-1" and keep other parameters as it is.
https://api.trade.gov/consolidated_screening_list/search?api_key=XXX&**size=-1**&countries=AF&fuzzy_name=false&sort=name:desc

this returns all records 9416 and appears it is not considering COUNTRIES filter at all.

To further verify working on SIZE=-1 I changed "COUNTRIES=abcabcab"
and API returns 9416 records whereas it should return Zero, isnt?
https://api.trade.gov/consolidated_screening_list/search?api_key=XXX&size=-1&countries=abcabcab&fuzzy_name=false&sort=name:desc

**Comment by kbecht** [comment]
size=-1 is not a valid parameter. Size needs to be set between 1 and 100. Why are you setting size to -1? Perhaps there's a better way to get the results you are looking for.

**Comment by infoBridge** [comment]
What is good way to fetch 1000 records than maximum of 100 records in a single API call?
thanks

**Comment by kbecht** [comment]
The two parameters you need to use are “size” and “offset”. The size parameter sets the number of results up to size = 100. After the first 100 results, you have to move the offset. To get the 2nd 100 results you’d say …size=100&offset=99 (the count starts at 0) and so on.

You can only get a full dump in one go by using the formatted file download; e.g., https://api.trade.gov/consolidated_screening_list/search.csv?api_key=APIKEY.

**Comment by infoBridge** [comment]
thank for the info. 
To address my case I would like to understand how frequently Data changes, Can I assume its once a DAY at a fixed known time?

also here is the link for another API, giving idea for SIZE=-1
https://developer.trade.gov/market-research-library.html

**Comment by kbecht** [comment]
The Consolidated Screening List does a fresh pull from the originating sources hourly. We try to keep it as up to date as possible.

I apologize for the suggestion of SIZE=-1 on the Market Research Library api page. I will have that removed from the page as it is no longer a function we support. Incidentally, we are in the process of retiring the Market Research Library api. It will be removed from our portal on Oct 1. If you use it, I recommend migrating to our Market Intelligence api instead. It is more up to date and should be more useful to you. If you have any questions about this retirement, I am happy to help you with that as well.

**Comment by infoBridge** [comment]
thank you for super responses. I have few answers to plan next moves.
Best!
* Github is the only way to reach you/ Team for prompt replies?

**Comment by kbecht** [comment]
I'm glad I could help. In addition to gitHub, you can also e-mail us at DataServices@trade.gov. I check that e-mail twice daily. If there's anything else you need, please let us know.
