### ISSUE TITLE
API to get dump in json format?

### ISSUE THREAD

**Issue by infoBridge** [InternationalTradeAdministration/developerportal#66]
For CSV dump link is https://api.trade.gov/consolidated_screening_list/search.csv?api_key=XXX

Do you support similar URL to get a full Dump in JSON format?

**Comment by kbecht** [comment]
Currently, the only options for downloading the entire list are:
CSV - https://api.trade.gov/consolidated_screening_list/search.csv?api_key={key}
TSV - https://api.trade.gov/consolidated_screening_list/search.tsv?api_key={key}

These lists are generated hourly when then API is updated. 

To obtain a full listing in JSON, you must use the size and offset parameters to retrieve the listing 100 records at a time. The size parameter allows you to configure the number of results to be returned. The offset parameter defines the offset from the first result you want to fetch. Unless specified the API returns 10 results at a time.
