### ISSUE TITLE
Formatting difference between CSV and JSON?

### ISSUE THREAD

**Issue by infoBridge** [InternationalTradeAdministration/developerportal#67]
in JSON format ADDRESS column data is properly marked with sub-elements like Address, City, state, postal etc whereas in CSV has single column "addresses" contains the data without marking for City, state, postal etc below is an example from JSON and CSV. CSV address column sometimes only has very few text like "AF" making it difficult to understand if the data present under the Addresses column is address/ city/ country etc. Is there any solution to address this?

**Json addresses**
address	"UPON THE DATE OF THE ORDER INCARCERATED AT USM NO: 26265-177, FCI SEAGOVILLE, 2113 NORTH HIGHWAY 175"
city	"SEAGOVILLE"
state	"TX"
postal_code	"75159"
country	"US"_

**CSV addresses**
example1: Zapopan, Jalisco, MX
example2: PA
example3: TR; SY

**Comment by kbecht** [comment]
I have logged this as an enhancement request. We will review it and then add it to the queue to be worked on. I will let you know as soon as I know more.

**Comment by kbecht** [comment]
We will work this change in next week. Please let me know if you have any additional ideas. We are always looking for new ways to improve on the service.

**Comment by infoBridge** [comment]
Thank you.

 

When this feature will be ready and will I be notified when its available to use?

 

Best

**Comment by kbecht** [comment]
When it is available, I will reply to this post to notify you.

**Comment by kbecht** [comment]
@infoBridge We have run into some issue doing this. I just wanted to let you know that we are still working on it.

**Comment by infoBridge** [comment]
thank you.
Will inform Team the same that the solution is in working.
