### ISSUE TITLE
Zip Code to USEAC API: Offeset > 9900 returns Internal Server Error

### ISSUE THREAD

**Issue by chris-rogala** [InternationalTradeAdministration/developerportal#68]
When paging through the Zip Code to USEAC API, it fails with an offset greater than 9900.  Also, the status code returned for the error is a 200 when it should be a 500. The content is:

```
{
    "status": 500,
    "error": "Internal Server Error"
}
```

The cURL for the request is:
```
GET /ita_zipcode_to_post/search?api_key={{api_key}}&amp; size=100&amp; offset=9901 HTTP/1.1
Host: api.trade.gov
cache-control: no-cache
```
I'm going to assume there is a log with the request id.  The value of the x-Request-Id is 16bb95c9-4061-4460-bb5a-09cf759be6c5.

**Comment by kbecht** [comment]
We have resolved this issue. You should have no problem using the offset to view the full data set. Please let me know if you continue to experience problems.
