### ISSUE TITLE
Missing 'sources_used' data from Consolidated Screening List API query

### ISSUE THREAD

**Issue by jdenright** [InternationalTradeAdministration/developerportal#70]
We are currently using your CSL API documented at 
https://developer.trade.gov/consolidated-screening-list.html

specifically at https://api.trade.gov/consolidated_screening_list/search

We are currently relying upon the sources_used data in the search result 
to know when a list has changed when using the API.  Is this a temporary 
issue, an intentional change, or some other issue?  Is there a new way 
to query the sources?

Between yesterday and today (2019-03-07), we used to get 'sources_used' 
(see below example returned data that has no results) when querying 
data.  Now we get this:

==============

Today

==============

{
   "total": 0,
   "offset": 0,
   "search_performed_at": "2019-03-07T05:03:40.631-05:00",
   "results": []
}

===============

Yesterday

=================

{
   "total": 0,
   "offset": 0,
   "sources_used": [
     {
       "source": "Denied Persons List (DPL) - Bureau of Industry and 
Security",
       "source_last_updated": "2019-02-05T12:03:08.941-05:00",
       "last_imported": "2019-03-06T05:03:07.126-05:00",
       "import_rate": "Hourly"
     },
     {
       "source": "ITAR Debarred (DTC) - State Department",
       "source_last_updated": "2018-06-27T22:07:14-04:00",
       "last_imported": "2019-03-06T05:03:04.69-05:00",
       "import_rate": "Hourly"
     },
     {
       "source": "Entity List (EL) - Bureau of Industry and Security",
       "source_last_updated": "2018-12-14T18:03:20.647-05:00",
       "last_imported": "2019-03-06T05:03:12.449-05:00",
       "import_rate": "Hourly"
     },
     {
       "source": "List of Persons Identified as Blocked Solely Pursuant 
to Executive Order 13599 (13599) - Treasury Department",
       "source_last_updated": "2019-02-07T13:03:09.761-05:00",
       "last_imported": "2019-03-06T05:03:05.046-05:00",
       "import_rate": "Hourly"
     },
     {
       "source": "Foreign Sanctions Evaders (FSE) - Treasury Department",
       "source_last_updated": "2019-02-07T13:03:13.136-05:00",
       "last_imported": "2019-03-06T05:03:05.72-05:00",
       "import_rate": "Hourly"
     },
     {
       "source": "Nonproliferation Sanctions (ISN) - State Department",
       "source_last_updated": "2018-07-20T16:03:06-04:00",
       "last_imported": "2019-03-06T05:03:04.976-05:00",
       "import_rate": "Hourly"
     },
     {
       "source": "Part 561 List (561) - Treasury Department",
       "source_last_updated": "2019-02-07T13:03:04.775-05:00",
       "last_imported": "2019-03-06T05:03:04.878-05:00",
       "import_rate": "Hourly"
     },
     {
       "source": "Palestinian Legislative Council List (PLC) - Treasury 
Department",
       "source_last_updated": "2019-02-07T13:03:13.554-05:00",
       "last_imported": "2019-03-06T05:03:05.083-05:00",
       "import_rate": "Hourly"
     },
     {
       "source": "Specially Designated Nationals (SDN) - Treasury 
Department",
       "source_last_updated": "2019-03-05T14:04:38.213-05:00",
       "last_imported": "2019-03-06T05:03:05.625-05:00",
       "import_rate": "Hourly"
     },
     {
       "source": "Sectoral Sanctions Identifications List (SSI) - 
Treasury Department",
       "source_last_updated": "2019-02-07T13:03:14.798-05:00",
       "last_imported": "2019-03-06T05:03:04.815-05:00",
       "import_rate": "Hourly"
     },
     {
       "source": "Unverified List (UVL) - Bureau of Industry and Security",
       "source_last_updated": "2018-06-06T09:52:07-04:00",
       "last_imported": "2019-03-06T05:03:08.153-05:00",
       "import_rate": "Hourly"
     }
   ],
   "search_performed_at": "2019-03-06T05:03:37.994-05:00",
   "results": []
}

**Comment by kbecht** [comment]
This was not an intentional change. We are working to get sources_used readded to the API. We do not yet have a timeline, but will let you know as soon as the problem has been resolved.

**Comment by hmpqf** [comment]
This appears to be fixed. Can you confirm?

**Comment by jamesisaacs** [comment]
Hi @hmpqf. This has been fixed. Thank you @jdenright for first reporting this issue.

**Comment by hmpqf** [comment]
Thank you!

**Comment by jdenright** [comment]
Done and Done! This problem is fixed. Thank you!

**Comment by patrick-mullen** [comment]
This issue appears to have resurfaced with the new API, can anyone confirm if this is again a bug or intentional?
@kbecht ?
