### ISSUE TITLE
Cannot sign-up

### ISSUE THREAD

**Issue by osf-dchristman** [InternationalTradeAdministration/developerportal#76]
System seems to accept my new user registration (would only allow me to use my email address once)... but the email confirmation never comes and the request new email confirmation function returns a 500 error

**Comment by jlhall** [comment]
Same situation, with the additional note that my account sign up from last week seems to have been removed, as my email is unrecognized for login, my old token/key for testing isn't valid (401), etc. I was able to initiate (re-initiate) sign up with the same email from last week, but never receive a confirmation and the re-send new confirmation flow 500s (as indicated above).

I did not receive an email indicating account closure/token banning, etc. (I'd be surprised if it was a ban, I've sent maybe a handful of requests, mostly via curl/insomnia rest client).

**Comment by jamesisaacs** [comment]
Hi. The problem is on our end. I'm looking into it. I will reach out to you if I see your information in the system. Please feel free to email me at james.isaacs@trade.gov.

**Comment by uszoom-liorz** [comment]
I am seeing the same problem here. I tried to register and got a 500 error. However my email address now appears to be in the system, as when I retry, I am told my email is already in use. Attempts to resend the verification email or reset the password also result in 500 errors.

**Comment by jamesisaacs** [comment]
This issue has been resolved. Thank you for your feedback.

**Comment by jlhall** [comment]
@jamesisaacs Thanks again!
