### ISSUE TITLE
Using the Consolidated List API with full address does not seem to work

### ISSUE THREAD

**Issue by uszoom-liorz** [InternationalTradeAdministration/developerportal#79]
I am trying to query the Consolidated List API to do a search by address. When I provide a _full address_ (in the format of (<street>,<City>,<State> ) that I _know_ belongs to someone on the list (I copied it out of the list search), I don't get any matches. If I provide only a portion of the address (Street, City, Zip, etc) I do get the matches I expect.

Is this expected behavior from the app? Am I just providing the full address info in the right format, or it impossible to search by more than one portion of an address at a time.

**Comment by kbecht** [comment]
I apologize for the delay in responding. I have been out of the office. 

Can you provide a sample string that you have been using? When I use the string below it works fine:

https://api.trade.gov/consolidated_screening_list/search?api_key={key}&address=%225599%20NW%2023rd%20Avenue%20Boca%20Raton%20FL%2033496%20US%22

%22 is the quote mark, so I have the full address in quotes.

**Comment by kbecht** [comment]
I seem to be having the same problem that you are with that address. I have asked our technical team to take a look at it.

**Comment by uszoom-liorz** [comment]
> I seem to be having the same problem that you are with that address. I have asked our technical team to take a look at it.

Is it possible this has something to do with the fact that my example (which fails) is in DPL and the one you gave is in SDN. Could the search be searching differently based on the data sources?

**Comment by kbecht** [comment]
I apologize for the delay. The technical team has found a bug and they are working to resolve it.

**Comment by vpoletae** [comment]
Hi Team! Could you please advise why access may be forbidden? previously everything worked fine. I got an access token but when I use it I see 403-Access forbidden. I'm trying to get access to Consolidated screening tool. Thank you!

**Comment by kbecht** [comment]
After launching our new API platform, we have been working on resolving this and we are close to a resolution. Thank you for your patience.

**Comment by jamesisaacs** [comment]
This bug has been addressed (couldn't resist). Closing this as fixed.
