### ISSUE TITLE
Characters returned wrongly

### ISSUE THREAD

**Issue by jkoprivak** [InternationalTradeAdministration/developerportal#91]
Hello, 
I am getting strange results while running queries from the sanction list "Entity List = EL".
For example in this query: https://api.trade.gov/consolidated_screening_list/search?api_key=prAGjb7avQKvwk07329K_OYe&q=Edward%20Fan 
you can see that the value "city" should be probably "Taiwan", but I am getting this result: 
 
![image](https://user-images.githubusercontent.com/40920531/63609690-e27d1700-c5d7-11e9-9d0d-0e65ee9e9b81.png)

The problem occurs in all browsers and different computers.
Can you please give me an advice? 
Thank you!

**Comment by jkoprivak** [comment]
Another example:
https://api.trade.gov/consolidated_screening_list/search?api_key=prAGjb7avQKvwk07329K_OYe&q=Aktsionernoe%20Obschestvo
value in name: "name":"Aktsionernoe Obschestvo Yaltinskaya Kinodstudiya"

**Comment by kbecht** [comment]
I have reviewed your examples and the source data file for the Entity List. These are caused by mistakes and special characters in the source data file from BIS. I have reached out to BIS requesting that someone review, update and resend the file.

**Comment by jkoprivak** [comment]
Thank you!

**Comment by kbecht** [comment]
I have not heard back from BIS, but I will reach out to them again. In the interim, I did some digging and the city entered above "Tai'an City" is a valid city name in the western Shandong province of China. 

The special characters I have been seeing in the source file are single apostrophes, such as:
Aktsionernoe Obschestvo ‘Yaltinskaya Kinodstudiya’
", Tai’an City"

Are you able to alter your application to accept single apostrophes?

**Comment by jkoprivak** [comment]
Yes I am.
Thank you!
