### ISSUE TITLE
Missing Programs from the CSL

### ISSUE THREAD

**Issue by terryhowelljr** [InternationalTradeAdministration/developerportal#95]
I sent an an email before realizing you have a github issue list...sorry about that.  

We access the consolidated_screening_list APIs on a daily basis and provide a user interface for our customers to perform OFAC screening.  
https://api.trade.gov/consolidated_screening_list/search.csv?api_key=mykey

We've noticed missing OFAC programs from the consolidated_screening_lists API throughout October and are curious if there is an issue on your end or do we need to account for missing OFAC programs in our logic? 

I would expect if an agency doesn't send a list that the prior list would continue to be served until they updated their list.  

**See below for examples:**
1. The **Nonproliferation Sanctions (ISN) - State Department** list goes missing during random days throughout the month.  Our example shows it missing on Oct 3rd and again on the 9th.  This particular list appears unreliable when reviewing all days across the month.  
2. **ITAR Debarred (DTC) - State Department** - list goes from 686 to 515 and then back to 686.  
![OFACAnalysisOct2019](https://user-images.githubusercontent.com/50846872/67796528-92e31d80-fa56-11e9-8f33-c60d6623f586.png)

**Comment by kbecht** [comment]
You are welcome to contact through both email (DataServices@trade.gov) and gitHub. We monitor both channels.

We are unaware of missing OFAC entries during the month of October. To the best of our knowledge, there was no outage. We are looking into this.

**Comment by kbecht** [comment]
For the last two weeks, we have monitored the number of entries in both the ISN and DTC lists and found them to be consistent. Based on recent email that you have also seen them as consistent, we will be closing this issue. Please feel free to reach out again if you experience any other issues.

**Comment by terryhowelljr** [comment]
I agree - after reviewing November data, the issue no longer exists.  We will continue to monitor and open another ticket if needed.  Thank you for your responsiveness.
